name: serverpod_flutter

packages:
  - apps/*
  - features/*
  - services/*
  - server/*

command:
  version:
    # Only allow versioning to happen on main branch.
    branch: develop

  bootstrap:
    environment:
      sdk: ">=3.4.0 <4.0.0"
      flutter: ">=3.24.0"

    dependencies:
      flutter_localizations:
        sdk: flutter
      fpdart: ^1.1.1
      flutter_riverpod: ^2.6.1
      riverpod_annotation: ^2.6.1
      go_router: ^14.6.1
      realm: ^20.0.0
      flutter_svg: ^2.0.15
      device_info_plus: ^11.1.1

    dev_dependencies:
      flutter_lints: ^5.0.0
      custom_lint:
      build_runner:
      riverpod_generator: ^2.6.1
      flutter_launcher_icons: "^0.14.2"
      go_router_builder: ^2.7.5

scripts:
  build_localization:
    exec: flutter gen-l10n && dart run build_runner build --delete-conflicting-outputs
