name: theme_config
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  intl: ^0.19.0
  flutter_svg: ^2.0.15
  timeago: ^3.7.0
  google_fonts: ^6.2.1

  # Services
  network_service: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.1
  build_runner: any
  custom_lint: any
  riverpod_lint: ^2.6.1

flutter:
  assets:
    - assets/message/

  # fonts:
  #   - family: NavIcons
  #     fonts:
  #       - asset: assets/fonts/NavIcons.ttf
